version: "2"
linters:
  default: all
  disable:
    - wsl # Deprecated in favour of wsl_v5
    - wsl_v5 # Overly opinionated
    - exhaustruct # Overly opinionated
    - varnamelen # Overly opinionated
    - noinlineerr # Inline errs is idiomatic
    - dupl # To be enabled later (easier to setup parsers with some duplication)
    - maintidx # To be enabled later (getting long tests in place before refactors)
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
            - "!$test"
          allow:
            - github.com/alec-w/ebnf-go
            - $gostd
          deny:
            - pkg: testing
        test:
          list-mode: strict
          files:
            - $test
          allow:
            - github.com/alec-w/ebnf-go
            - $gostd
    nolintlint:
      require-specific: true
      require-explanation: true
    ireturn:
      allow:
        - error
        - generic

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
run:
  timeout: 1m
